{-
   OpenFEC

   This API allows you to explore the way candidates and committees fund their campaigns.    The FEC API is a RESTful web service supporting full-text and field-specific searches on FEC data. [Bulk downloads](https://www.fec.gov/data/advanced/?tab=bulk-data) are available on the current site. Information is tied to the underlying forms by file ID and image ID. Data is updated nightly.    There is a lot of data, but a good place to start is to use search to find interesting candidates and committees. Then, you can use their IDs to find report or line item details with the other endpoints. If you are interested in individual donors, check out contributor information in schedule_a.    Get an [API key here](https://api.data.gov/signup/). That will enable you to place up to 1,000 calls an hour. Each call is limited to 100 results per page. You can email questions, comments or a request to get a key for 120 calls per minute to [APIinfo@fec.gov](mailto:apiinfo@fec.gov). You can also ask questions and discuss the data in the [FEC data Google Group](https://groups.google.com/forum/#!forum/fec-data). API changes will also be added to this group in advance of the change.       The model definitions and schema are available at [/swagger](/swagger/). This is useful for making wrappers and exploring the data.    A few restrictions limit the way you can use FEC data. For example, you can’t use contributor lists for commercial purposes or to solicit donations. [Learn more here](https://transition.fec.gov/pages/brochures/saleuse.shtml).    [View our source code](https://github.com/fecgov/openFEC). We welcome issues and pull requests!

   OpenAPI spec version: 2.0
   OpenFEC API version: 1.0
   Generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
-}

{-|
Module : OpenFEC.API.Efiling
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module OpenFEC.API.Efiling where

import OpenFEC.Core
import OpenFEC.MimeTypes
import OpenFEC.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Efiling

-- *** efileFilingsGet

-- | @GET \/efile\/filings\/@
-- 
-- Basic information about electronic files coming into the FEC, posted as they are received.
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
efileFilingsGet 
  :: ApiKey -- ^ "apiKey" -   API key for https://api.data.gov. Get one at https://api.data.gov/signup. 
  -> OpenFECRequest EfileFilingsGet MimeNoContent EFilingsPage MimeJSON
efileFilingsGet (ApiKey apiKey) =
  _mkRequest "GET" ["/efile/filings/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setQuery` toQuery ("api_key", Just apiKey)

data EfileFilingsGet  

-- | /Optional Param/ "sort_null_only" - Toggle that filters out all rows having sort column that is non-null
instance HasOptionalParam EfileFilingsGet SortNullOnly where
  applyOptionalParam req (SortNullOnly xs) =
    req `setQuery` toQuery ("sort_null_only", Just xs)

-- | /Optional Param/ "file_number" - Filing ID number
instance HasOptionalParam EfileFilingsGet FileNumber where
  applyOptionalParam req (FileNumber xs) =
    req `setQuery` toQueryColl MultiParamArray ("file_number", Just xs)

-- | /Optional Param/ "max_receipt_date" - Selects all items received by FEC before this date or datetime
instance HasOptionalParam EfileFilingsGet MaxReceiptDateDateTime where
  applyOptionalParam req (MaxReceiptDateDateTime xs) =
    req `setQuery` toQuery ("max_receipt_date", Just xs)

-- | /Optional Param/ "sort" - Provide a field to sort by. Use - for descending order.
instance HasOptionalParam EfileFilingsGet SortText where
  applyOptionalParam req (SortText xs) =
    req `setQuery` toQuery ("sort", Just xs)

-- | /Optional Param/ "committee_id" -  A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits. 
instance HasOptionalParam EfileFilingsGet CommitteeId where
  applyOptionalParam req (CommitteeId xs) =
    req `setQuery` toQueryColl MultiParamArray ("committee_id", Just xs)

-- | /Optional Param/ "min_receipt_date" - Selects all items received by FEC after this date or datetime
instance HasOptionalParam EfileFilingsGet MinReceiptDateDateTime where
  applyOptionalParam req (MinReceiptDateDateTime xs) =
    req `setQuery` toQuery ("min_receipt_date", Just xs)

-- | /Optional Param/ "page" - For paginating through results, starting at page 1
instance HasOptionalParam EfileFilingsGet Page where
  applyOptionalParam req (Page xs) =
    req `setQuery` toQuery ("page", Just xs)

-- | /Optional Param/ "per_page" - The number of results returned per page. Defaults to 20.
instance HasOptionalParam EfileFilingsGet PerPage where
  applyOptionalParam req (PerPage xs) =
    req `setQuery` toQuery ("per_page", Just xs)

-- | /Optional Param/ "sort_hide_null" - Hide null values on sorted column(s).
instance HasOptionalParam EfileFilingsGet SortHideNull where
  applyOptionalParam req (SortHideNull xs) =
    req `setQuery` toQuery ("sort_hide_null", Just xs)
-- | @application/json@
instance Produces EfileFilingsGet MimeJSON


-- *** efileReportsHouseSenateGet

-- | @GET \/efile\/reports\/house-senate\/@
-- 
--  Key financial data reported periodically by committees as they are reported. This feed includes summary information from the the House F3 reports, the presidential F3p reports and the PAC and party F3x reports.  Generally, committees file reports on a quarterly or monthly basis, but some must also submit a report 12 days before primary elections. Therefore, during the primary season, the period covered by this file may be different for different committees. These totals also incorporate any changes made by committees, if any report covering the period is amended.  DISCLAIMER: The field labels contained within this resource are subject to change.  We are attempting to succinctly label these fields while conveying clear meaning to ensure accessibility for all users. 
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
efileReportsHouseSenateGet 
  :: ApiKey -- ^ "apiKey" -   API key for https://api.data.gov. Get one at https://api.data.gov/signup. 
  -> OpenFECRequest EfileReportsHouseSenateGet MimeNoContent BaseF3FilingPage MimeJSON
efileReportsHouseSenateGet (ApiKey apiKey) =
  _mkRequest "GET" ["/efile/reports/house-senate/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setQuery` toQuery ("api_key", Just apiKey)

data EfileReportsHouseSenateGet  

-- | /Optional Param/ "sort_null_only" - Toggle that filters out all rows having sort column that is non-null
instance HasOptionalParam EfileReportsHouseSenateGet SortNullOnly where
  applyOptionalParam req (SortNullOnly xs) =
    req `setQuery` toQuery ("sort_null_only", Just xs)

-- | /Optional Param/ "file_number" - Filing ID number
instance HasOptionalParam EfileReportsHouseSenateGet FileNumber where
  applyOptionalParam req (FileNumber xs) =
    req `setQuery` toQueryColl MultiParamArray ("file_number", Just xs)

-- | /Optional Param/ "max_receipt_date" - Selects all items received by FEC before this date or datetime
instance HasOptionalParam EfileReportsHouseSenateGet MaxReceiptDateDateTime where
  applyOptionalParam req (MaxReceiptDateDateTime xs) =
    req `setQuery` toQuery ("max_receipt_date", Just xs)

-- | /Optional Param/ "sort" - Provide a field to sort by. Use - for descending order.
instance HasOptionalParam EfileReportsHouseSenateGet SortText where
  applyOptionalParam req (SortText xs) =
    req `setQuery` toQuery ("sort", Just xs)

-- | /Optional Param/ "committee_id" -  A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits. 
instance HasOptionalParam EfileReportsHouseSenateGet CommitteeId where
  applyOptionalParam req (CommitteeId xs) =
    req `setQuery` toQueryColl MultiParamArray ("committee_id", Just xs)

-- | /Optional Param/ "min_receipt_date" - Selects all items received by FEC after this date or datetime
instance HasOptionalParam EfileReportsHouseSenateGet MinReceiptDateDateTime where
  applyOptionalParam req (MinReceiptDateDateTime xs) =
    req `setQuery` toQuery ("min_receipt_date", Just xs)

-- | /Optional Param/ "page" - For paginating through results, starting at page 1
instance HasOptionalParam EfileReportsHouseSenateGet Page where
  applyOptionalParam req (Page xs) =
    req `setQuery` toQuery ("page", Just xs)

-- | /Optional Param/ "per_page" - The number of results returned per page. Defaults to 20.
instance HasOptionalParam EfileReportsHouseSenateGet PerPage where
  applyOptionalParam req (PerPage xs) =
    req `setQuery` toQuery ("per_page", Just xs)

-- | /Optional Param/ "sort_hide_null" - Hide null values on sorted column(s).
instance HasOptionalParam EfileReportsHouseSenateGet SortHideNull where
  applyOptionalParam req (SortHideNull xs) =
    req `setQuery` toQuery ("sort_hide_null", Just xs)
-- | @application/json@
instance Produces EfileReportsHouseSenateGet MimeJSON


-- *** efileReportsPacPartyGet

-- | @GET \/efile\/reports\/pac-party\/@
-- 
--  Key financial data reported periodically by committees as they are reported. This feed includes summary information from the the House F3 reports, the presidential F3p reports and the PAC and party F3x reports.  Generally, committees file reports on a quarterly or monthly basis, but some must also submit a report 12 days before primary elections. Therefore, during the primary season, the period covered by this file may be different for different committees. These totals also incorporate any changes made by committees, if any report covering the period is amended.  DISCLAIMER: The field labels contained within this resource are subject to change.  We are attempting to succinctly label these fields while conveying clear meaning to ensure accessibility for all users. 
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
efileReportsPacPartyGet 
  :: ApiKey -- ^ "apiKey" -   API key for https://api.data.gov. Get one at https://api.data.gov/signup. 
  -> OpenFECRequest EfileReportsPacPartyGet MimeNoContent BaseF3XFilingPage MimeJSON
efileReportsPacPartyGet (ApiKey apiKey) =
  _mkRequest "GET" ["/efile/reports/pac-party/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setQuery` toQuery ("api_key", Just apiKey)

data EfileReportsPacPartyGet  

-- | /Optional Param/ "sort_null_only" - Toggle that filters out all rows having sort column that is non-null
instance HasOptionalParam EfileReportsPacPartyGet SortNullOnly where
  applyOptionalParam req (SortNullOnly xs) =
    req `setQuery` toQuery ("sort_null_only", Just xs)

-- | /Optional Param/ "file_number" - Filing ID number
instance HasOptionalParam EfileReportsPacPartyGet FileNumber where
  applyOptionalParam req (FileNumber xs) =
    req `setQuery` toQueryColl MultiParamArray ("file_number", Just xs)

-- | /Optional Param/ "max_receipt_date" - Selects all items received by FEC before this date or datetime
instance HasOptionalParam EfileReportsPacPartyGet MaxReceiptDateDateTime where
  applyOptionalParam req (MaxReceiptDateDateTime xs) =
    req `setQuery` toQuery ("max_receipt_date", Just xs)

-- | /Optional Param/ "sort" - Provide a field to sort by. Use - for descending order.
instance HasOptionalParam EfileReportsPacPartyGet SortText where
  applyOptionalParam req (SortText xs) =
    req `setQuery` toQuery ("sort", Just xs)

-- | /Optional Param/ "committee_id" -  A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits. 
instance HasOptionalParam EfileReportsPacPartyGet CommitteeId where
  applyOptionalParam req (CommitteeId xs) =
    req `setQuery` toQueryColl MultiParamArray ("committee_id", Just xs)

-- | /Optional Param/ "min_receipt_date" - Selects all items received by FEC after this date or datetime
instance HasOptionalParam EfileReportsPacPartyGet MinReceiptDateDateTime where
  applyOptionalParam req (MinReceiptDateDateTime xs) =
    req `setQuery` toQuery ("min_receipt_date", Just xs)

-- | /Optional Param/ "page" - For paginating through results, starting at page 1
instance HasOptionalParam EfileReportsPacPartyGet Page where
  applyOptionalParam req (Page xs) =
    req `setQuery` toQuery ("page", Just xs)

-- | /Optional Param/ "per_page" - The number of results returned per page. Defaults to 20.
instance HasOptionalParam EfileReportsPacPartyGet PerPage where
  applyOptionalParam req (PerPage xs) =
    req `setQuery` toQuery ("per_page", Just xs)

-- | /Optional Param/ "sort_hide_null" - Hide null values on sorted column(s).
instance HasOptionalParam EfileReportsPacPartyGet SortHideNull where
  applyOptionalParam req (SortHideNull xs) =
    req `setQuery` toQuery ("sort_hide_null", Just xs)
-- | @application/json@
instance Produces EfileReportsPacPartyGet MimeJSON


-- *** efileReportsPresidentialGet

-- | @GET \/efile\/reports\/presidential\/@
-- 
--  Key financial data reported periodically by committees as they are reported. This feed includes summary information from the the House F3 reports, the presidential F3p reports and the PAC and party F3x reports.  Generally, committees file reports on a quarterly or monthly basis, but some must also submit a report 12 days before primary elections. Therefore, during the primary season, the period covered by this file may be different for different committees. These totals also incorporate any changes made by committees, if any report covering the period is amended.  DISCLAIMER: The field labels contained within this resource are subject to change.  We are attempting to succinctly label these fields while conveying clear meaning to ensure accessibility for all users. 
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
efileReportsPresidentialGet 
  :: ApiKey -- ^ "apiKey" -   API key for https://api.data.gov. Get one at https://api.data.gov/signup. 
  -> OpenFECRequest EfileReportsPresidentialGet MimeNoContent BaseF3PFilingPage MimeJSON
efileReportsPresidentialGet (ApiKey apiKey) =
  _mkRequest "GET" ["/efile/reports/presidential/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setQuery` toQuery ("api_key", Just apiKey)

data EfileReportsPresidentialGet  

-- | /Optional Param/ "sort_null_only" - Toggle that filters out all rows having sort column that is non-null
instance HasOptionalParam EfileReportsPresidentialGet SortNullOnly where
  applyOptionalParam req (SortNullOnly xs) =
    req `setQuery` toQuery ("sort_null_only", Just xs)

-- | /Optional Param/ "file_number" - Filing ID number
instance HasOptionalParam EfileReportsPresidentialGet FileNumber where
  applyOptionalParam req (FileNumber xs) =
    req `setQuery` toQueryColl MultiParamArray ("file_number", Just xs)

-- | /Optional Param/ "max_receipt_date" - Selects all items received by FEC before this date or datetime
instance HasOptionalParam EfileReportsPresidentialGet MaxReceiptDateDateTime where
  applyOptionalParam req (MaxReceiptDateDateTime xs) =
    req `setQuery` toQuery ("max_receipt_date", Just xs)

-- | /Optional Param/ "sort" - Provide a field to sort by. Use - for descending order.
instance HasOptionalParam EfileReportsPresidentialGet SortText where
  applyOptionalParam req (SortText xs) =
    req `setQuery` toQuery ("sort", Just xs)

-- | /Optional Param/ "committee_id" -  A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits. 
instance HasOptionalParam EfileReportsPresidentialGet CommitteeId where
  applyOptionalParam req (CommitteeId xs) =
    req `setQuery` toQueryColl MultiParamArray ("committee_id", Just xs)

-- | /Optional Param/ "min_receipt_date" - Selects all items received by FEC after this date or datetime
instance HasOptionalParam EfileReportsPresidentialGet MinReceiptDateDateTime where
  applyOptionalParam req (MinReceiptDateDateTime xs) =
    req `setQuery` toQuery ("min_receipt_date", Just xs)

-- | /Optional Param/ "page" - For paginating through results, starting at page 1
instance HasOptionalParam EfileReportsPresidentialGet Page where
  applyOptionalParam req (Page xs) =
    req `setQuery` toQuery ("page", Just xs)

-- | /Optional Param/ "per_page" - The number of results returned per page. Defaults to 20.
instance HasOptionalParam EfileReportsPresidentialGet PerPage where
  applyOptionalParam req (PerPage xs) =
    req `setQuery` toQuery ("per_page", Just xs)

-- | /Optional Param/ "sort_hide_null" - Hide null values on sorted column(s).
instance HasOptionalParam EfileReportsPresidentialGet SortHideNull where
  applyOptionalParam req (SortHideNull xs) =
    req `setQuery` toQuery ("sort_hide_null", Just xs)
-- | @application/json@
instance Produces EfileReportsPresidentialGet MimeJSON

